1.- Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. Expected Output: Original List: [12.23, 13.32, 100, 36.32] One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [1]:
import numpy as np
l_list = [12.23, 13.32, 100, 36.32]
x= np.array(l_list)
print("Resultado: ",x)

Resultado:  [  12.23   13.32  100.     36.32]


2.- Write a Python program to create a null vector of size 10 and update sixth value to 11. 

In [2]:
import numpy as np
y = np.zeros(10)
print("Val")
y[6] = 11
print(x)



Val
[  12.23   13.32  100.     36.32]


 3.- Write a Python program to create a array with values ranging from 12 to 38.

In [4]:
import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


4.-  Write a Python program to reverse an array (first element becomes last). 

In [3]:
import numpy as np
import numpy as np
y = np.arange(12, 38)
print("Inv")
y = y[::-1]
print(y)

Inv
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13
 12]


 5.-WriteaPythonprogramtocreatea2darraywith1ontheborderand0inside.Expected Output: Original array: [[ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.]] 1 on the border and 0 inside in the array [[ 1. 1. 1. 1. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 1. 1. 1. 1.]] 

In [4]:
import numpy as np
x = np.ones((5,5))
print("zeros a la mitad")
x[1:-1,1:-1] = 0
print(x)

zeros a la mitad
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


6.-  Write a Python program to add a border (filled with 0’s) around an existing array. 

In [5]:
import numpy as np
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


7- Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern Checkerboard pattern: [[0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0]] hint: Explore the use of x[a :: b,:: c]= d,x[:: e,f :: g]= h, where the letters are integer numbers. 

In [6]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 8.- Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. Sample Array [0, 12, 45.21 ,34, 99.91] Expected Output: Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91] ValuesinCentigradedegrees:[-17.77777778-11.111111117.338888891.1111111137.72777778]. Usefunctionsandlistcomprehensionreadthelinkhttps://www.pythonforbeginners. com/lists/list-comprehensions-in-python/, to additional information about of list comprehension in python. 

In [7]:
import numpy as np
valores = [0, 12, 45.21, 34, 99.91]
x = np.array(valores)
print("Fahrenheit")
print(x)
print("Centigrados") 
print(5*x/9 - 5*32/9)

Fahrenheit
[  0.    12.    45.21  34.    99.91]
Centigrados
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


9.-  Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. Expected Output: Array1: [ 0 10 20 40 60 80] Array2: [10, 30, 40, 50, 70, 90] Set difference between two arrays: [ 0 20 60 80] 

In [9]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70, 90] 
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70, 90]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


10.- Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0’s elsewhere.

In [10]:
import numpy as np
x =  np.diagflat([4, 5, 6, 8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
